### ISSUE TITLE
[Bug]: Reseting settings x turning off all tp

### ISSUE THREAD

**Issue by Mafy-17** [ManasMods/CloudSettings#6]
### Minecraft Version

1.19

### Mod Loader

Fabric

### Architectury Version

latest

### CloudSettings Version

1.0.0.0 1.19

### Steps to Reproduce the Bug

Install mod 
start the game
close the game
start the game everything reset  always

### Expected Behavior

nothing would reset and texture[resource] packs that we're loaded before closing the game should stay loaded on next starting of game

### Actual Behavior

some stuff reset like mouse sensitivity mod config/settings and all texture[resource] packs unload

**Comment by Charismara** [comment]
Could you upload your `latest.log` file to [https://mclo.gs/](https://mclo.gs/) please?

**Comment by Mafy-17** [comment]
> Could you upload your `latest.log` file to https://mclo.gs/ please?

https://mclo.gs/cIcCIu7  here ya go sorry i couldn't reply sooner

**Comment by Mafy-17** [comment]
I should say that same thing sometimes happens only with sodium iris phosphor  lithium and cloud settings aswell

**Comment by Charismara** [comment]
There seems to be an issue with something in your resource pack config. [see here](https://mclo.gs/cIcCIu7#L1905)

Could you send me a screenshot of your resourcepack folder (the files in that folder)?

**Comment by Mafy-17** [comment]
![image](https://user-images.githubusercontent.com/92233613/205439631-f35ac270-1a44-4f32-afa1-03505a1e296e.png) mc folder
![image](https://user-images.githubusercontent.com/92233613/205439659-53c10edc-b256-4ec2-bbca-eec7ed2c4956.png) how it is after every start of mc
![image](https://user-images.githubusercontent.com/92233613/205439700-ff161983-83b5-4157-9893-f09048dd8ab5.png) what it should be I also sometimes include better bed tp

**Comment by Charismara** [comment]
hmm looks like i need to investigate this a bit more. 

Sorry for the inconvenience and thank you for reporting this :)

**Comment by Mafy-17** [comment]
Alr

**Comment by Charismara** [comment]
# Fixed in 1.0.0.1
Thank you for Reporting

**Comment by Mafy-17** [comment]
I am sad to re-ignite this bug but now resolution changes every start :( [texture packs still get unloaded]
version 1.0.0.1 1.19 :(

**Comment by Charismara** [comment]
Could you upload your latest.log file to https://mclo.gs/ please?

**Comment by Charismara** [comment]
I was able to reproduce the resolution bug which is caused though the fact that minecraft doesn't save it's config when changing the resolution slider to `current`. I guess i need to think about an workaround for that

**Comment by Charismara** [comment]
opened a new issue for that 

- [ ] #9
